import { useState } from 'react';
import { Button } from '../ui/button'
import { Select } from '../ui/select'
import { Checkbox } from '../ui/checkbox'
import axios from 'axios';
import {  getUserIdFromToken, getTokenFromCookies } from '@/lib/utils';

export const ChatAssistantBuilder: React.FC = () => {
    const [personality, setPersonality] = useState('');
    const [interests, setInterests] = useState<string[]>([]);
    const [assistantName, setAssistantName] = useState('');
    const [assistantBackground, setAssistantBackground] = useState('');
    const [loading, setLoading] = useState(false);
    const token = getTokenFromCookies()
    const userId = getUserIdFromToken()
  const personalities = [
    { label: 'Friendly', value: 'Friendly' },
    { label: 'Formal', value: 'Formal' },
    { label: 'Humorous', value: 'Humorous' },
    { label: 'Serious', value: 'Serious' },
  ];
    
    // Interests options (users can select multiple)
    const availableInterests = [
        'Travel',
        'Food',
        'Music',
        'Culture',
        'History',
        'Sports',
        'Games',
        'Philosophy',
        'Nature',
        'Gardening',
      ];

    const handleGenerateAssistant = async () => {
        setLoading(true);
        try {
            const response = await axios.post('http://localhost:4000/assistant/generate', {
                personality,
                interests,
                userId
            }, {
                withCredentials: true,
                headers: {
                  Authorization: `Bearer ${token}`,
                },
              });
            setAssistantName(response.data.name);  // Name generated by backend
            setAssistantBackground(response.data.background);  // Background generated
        } catch (error) {
            console.error('Error generating assistant:', error);
        } finally {
            setLoading(false);
        }
    };

     // Handle interest changes
  const handleInterestChange = (interest: string, isChecked: boolean) => {
    if (isChecked) {
      // Add interest if checked
      setInterests((prevInterests) => [...prevInterests, interest]);
    } else {
      // Remove interest if unchecked
      setInterests((prevInterests) => prevInterests.filter((i) => i !== interest));
    }
  };

    return (
        <div className="assistant-builder-container">
            <h1>Create Your Assistant</h1>

            {/* Step 1: Choose personality */}
            <label>Select Assistant Personality:</label>
            <Select
                options={personalities} // Array of options
                value={personality} // Current selected value
                onChange={setPersonality} // Update state on change
            />

            {/* Step 2: Choose interests */}
            <label>Select Assistant Interests:</label>
            {availableInterests.map((interest) => (
                <Checkbox
                key={interest}
                label={interest} // Label to display
                checked={interests.includes(interest)} // Check if interest is selected
                onChange={(isChecked) => handleInterestChange(interest, isChecked)} // Handle change
                />
            ))}

            {/* Generate Assistant Button */}
            <Button onClick={handleGenerateAssistant} disabled={loading || !personality}>
                {loading ? 'Generating Assistant...' : 'Generate Assistant'}
            </Button>

            {/* Display generated assistant name and background */}
            {assistantName && (
                <div className="assistant-preview">
                    <h2>{assistantName}</h2>
                    <p>{assistantBackground}</p>
                </div>
            )}
        </div>
    );
};

export default ChatAssistantBuilder;
